Rewrite tauri_plugin_localhost to fix Linux resource loading issues
Uni-Gal/Ayaka pull request #39
Opened 2022-11-30 11:47 UTC by Tim-Paik

2022-11-30 13:29 UTC, Berrysoft requested changes

2022-11-30 13:29 UTC, Berrysoft commented on bins/ayaka-gui/src-tauri/src/asset_resolver.rs
> +                    if req.url().starts_with("/assets/")
`req.url()` 调用次数太多了，就算是常数复杂度也看起来有点啰嗦。

2022-11-30 13:29 UTC, Berrysoft commented on bins/ayaka-gui/src-tauri/src/asset_resolver.rs
> +                            let mut resp = Response::from_data(asset.bytes);
```suggestion
                            let mut resp = tiny_http::Response::from_data(asset.bytes);
```

2022-11-30 13:29 UTC, Berrysoft commented on bins/ayaka-gui/src-tauri/src/asset_resolver.rs
> +                        let mut resp = if let Some(csp) = asset.csp_header {
反正我们也是允许所有csp的，还需要检查吗

2022-11-30 13:29 UTC, Berrysoft commented on bins/ayaka-gui/src-tauri/src/asset_resolver.rs
> +                    match (req.url(), std::fs::canonicalize(req.url())) {
从前端请求过来一个 Windows 路径 `D:\foo\bar` ，这里面的 `req.url()` 是什么？

2022-11-30 13:29 UTC, Berrysoft commented on bins/ayaka-gui/src-tauri/src/asset_resolver.rs
> +                                let path = if req.url().ends_with('/') {
用 `url` crate 会不会更好

2022-11-30 13:29 UTC, Berrysoft commented on bins/ayaka-gui/src-tauri/src/asset_resolver.rs
> +                                    minreq::get(dev_url.trim_end_matches('/').to_string() + &path)
同问使用 `url` crate

2022-11-30 13:29 UTC, Berrysoft commented on bins/ayaka-gui/src-tauri/src/asset_resolver.rs
> +                    #[cfg(debug_assertions)]
`#[cfg(xxx)]` 和 `#[cfg(not(xxx))]` 成对出现，用 `if cfg!(xxx)` 或者 `cfg_if!` 吧

2022-11-30 13:29 UTC, Berrysoft commented on bins/ayaka-gui/src-tauri/src/asset_resolver.rs
> +                            let file = if file.metadata().unwrap().is_dir() {
Windows 上目录是无法直接 open 的（需要特殊的 flag），应该先判断是不是目录。

2022-11-30 16:21 UTC, Berrysoft requested changes

2022-11-30 16:21 UTC, Berrysoft commented on bins/ayaka-gui/src-tauri/src/asset_resolver.rs
> +                    let url = req.url().to_string();
不要 to_string

2022-11-30 16:21 UTC, Berrysoft commented on bins/ayaka-gui/src-tauri/src/asset_resolver.rs
> +                        let resp = minreq::get(dev_url.trim_end_matches('/').to_string() + &path)
```suggestion
                        let mut req_url = url::Url::parse(dev_url).unwrap().join(url).unwrap();
                        if req_url.path_segments().unwrap().last().unwrap_or_default().is_empty() {
                            req_url = req_url.join("index.html").unwrap();
                        }
                        let resp = minreq::get(req_url)
```

2022-12-01 01:57 UTC, Tim-Paik commented on bins/ayaka-gui/src-tauri/src/asset_resolver.rs
> +                        let resp = minreq::get(dev_url.trim_end_matches('/').to_string() + &path)
Fixed

2022-12-01 02:00 UTC, Tim-Paik commented on bins/ayaka-gui/src-tauri/src/asset_resolver.rs
> +                    let url = req.url().to_string();
Tauri 写死了的要求传入 String，我也没办法
![asset_resolver](https://user-images.githubusercontent.com/49786711/204947890-b3b7d330-4fc4-49e0-bdae-d9b6242fb4ec.png)
![to_string](https://user-images.githubusercontent.com/49786711/204947760-c1f19fff-9feb-4057-b625-bbeeb7d7778d.png)

2022-12-01 02:59 UTC, Berrysoft requested changes

2022-12-01 02:59 UTC, Berrysoft commented on bins/ayaka-gui/src-tauri/src/asset_resolver.rs
> +
格式：不要空行

2022-12-01 02:59 UTC, Berrysoft commented on bins/ayaka-gui/src-tauri/src/asset_resolver.rs
> +                        let file = if path.is_file() || path.is_symlink() {
为什么要判断符号链接

2022-12-01 02:59 UTC, Berrysoft commented on bins/ayaka-gui/src-tauri/src/asset_resolver.rs
> +                            let mut path = path.clone();
不要clone+push，用join

2022-12-01 02:59 UTC, Berrysoft commented on bins/ayaka-gui/src-tauri/src/main.rs
>  #![feature(absolute_path)]
这个feature应该用不到了吧，可以删掉

2022-12-01 02:59 UTC, Berrysoft commented on bins/ayaka-gui/src-tauri/src/main.rs
> +fn absolute_path(_storage: State<'_, Storage>, path: String) -> CommandResult<String> {
storage用不到可以不写。

这样的话也没必要在这里搞一个函数吧，这个逻辑可以放进前端。如果你拿不准怎么搞也可以先放在这里以后我搞

2022-12-01 04:37 UTC, merged